### ISSUE TITLE
removed lore from bashrc and get warnings?

### ISSUE THREAD

**Issue by albjeremias** [bashup/lore#2]
i'm getting this warning on my bash everytime i run a script:
`lore must be sourced into your shell before use; try 'source /home/ajeremias/.local/bin/lore' first`

why? I added lore by adding this line to my .bashrc, which i removed now.

`source /home/ajeremias/.local/bin/lore on`

**Comment by pjeby** [comment]
It looks like you saved your environment variables (specifically PROMPT_COMMAND) while lore was active.  Remove the `{ lore prompt;};` from that variable to uninstall completely.
