### ISSUE TITLE
trying tabby to load commands per pane 

### ISSUE THREAD

**Issue by albjeremias** [bashup/lore#3]
I've been trying out together lore + tabby. didn't work out so good. 

each pane gets exactly the same history... how I did it:
copy the lore script to
`.local/bin/lore`

`chmod +x .local/bin/lore`

added to .bashrc

`source /home/ajeremias/.local/bin/lore on`

also created an issue in tabby:
https://github.com/Eugeny/tabby/issues/7687

and now removed from .bashrc.. https://github.com/bashup/lore/issues/2

**Comment by pjeby** [comment]
Each session gets the same history unless you select a different global history file per pane.  Lore's tmux support works by asking tmux to identify the window number and pane number, but if tabby doesn't have an id mechanism like that there would be no way for lore to know which history file is wanted.
