### ISSUE TITLE
sourcing in zsh: console output produced during zsh initialization 

### ISSUE THREAD

**Issue by davidgamero** [bashup/lore#4]
Hey! I'm using zsh, and the instant prompt feature is taking issue with this bit being output to the terminal every time i source `lore`.

```
lore () {
        local REPLY
        declare -F lore::on-load &> /dev/null || source "$LORE_SOURCE" --
        (($#)) || set -- help
        ! declare -F lore."$1" &> /dev/null || {
                lore."$@"
                return
        }
        case $1 in
                (--) shift
                        ((!$#)) || lore "$@" ;;
                (-h | --help) lore help ;;
                (*) return 64 ;;
        esac
}
```

I've tried to hunt for where the output is coming from unsuccessfully, and was wondering if it's just a bash vs zsh compatibility thing. 
Ideally it wouldn't print anything to stdout when sourcing the file

Any help would be appreciated!

**Comment by davidgamero** [comment]
welp, i was able to get around this by just commenting out line 34 `#export -f lore` and everything seems to still be working 😄 

i'll leave this here in case someone else runs into the same issue

**Comment by pjeby** [comment]
The export -f is so you can put it in `.bash_profile` and only load it once without reloading it in subshells.

**Comment by davidgamero** [comment]
Oh okay that makes sense

I don't know why zsh would print out the function definition when calling the export on it then

**Comment by pjeby** [comment]
Me either!  :wink:
